### ISSUE TITLE
Negative cache confusion

### ISSUE THREAD

**Issue by How-Wang** [kdiAAA/TDA#5]
Thanks for your brilliant work!

But I wonder 
![截圖 2024-06-26 晚上11 49 47](https://github.com/kdiAAA/TDA/assets/62500402/b0ff3e97-d6ce-4572-ac39-f31a507414b8)
![截圖 2024-06-26 晚上11 50 00](https://github.com/kdiAAA/TDA/assets/62500402/67ea0c6b-8ac3-4d08-aeb0-ea1c3f620d97)

1. If we want to remove the uncertain class in a medium entropy scenario, we should "subtract" the negative label. However, in your paper, you use two negative signs, which would "add" the confusing class to the final probabilistic distribution. Is there a mistake here, or am I misunderstanding the purpose of the negative cache?

2. If we choose negative pseudo labels with probabilities higher than 𝑝𝑙 , wouldn't that also include the correct class label? Since our goal is to reduce the probabilities of incorrect classes, not the correct one, why do you choose negative pseudo labels with higher probabilities instead of excluding the highest probability (correct) class first?

Thank you!

**Comment by kdiAAA** [comment]
Hello,

Thank you for your interest in our work and apologize for the delayed response; I was on vacation. Here are the answers to your questions:

1. Thank you for pointing out the confusion regarding double negatives. In our paper, the use of multiple negative signs may appear redundant because we also account for the negative alpha parameter in the adaptation function. However, in our implementation, we apply the negative term only once, specifically at the final stage when we process the output from the negative cache. This ensures that the negative term is handled correctly in the negative cache design. We appreciate your pointing this out as it highlights an area of potential confusion in our method's description.

2. Regarding your second question, we initially experimented with an idea to exclude the highest probability class (often the correct class) from the negative cache's influence by introducing an upper threshold hyperparameter. This approach only yielded a marginal improvement of 0.1% on the ImageNet dataset. Consequently, we decided against adopting this method as it introduced extra complexity with minimal performance gain.

Thank you for these insightful questions, and hope this helps clarify your queries!

Best,
Adilbek
